const types = {
  // get bot list from server
  GET_BOTS_START: 'GET_BOTS_START',
  GET_BOTS_SUCCESS: 'GET_BOTS_SUCCESS',
  GET_BOTS_ERROR: 'GET_BOTS_ERROR',

  // get certain chat
  GET_CHAT_START: 'GET_CHAT_START',
  GET_CHAT_SUCCESS: 'GET_CHAT_SUCCESS',
  GET_CHAT_ERROR: 'GET_CHAT_ERROR',

  // post new message
  POST_MESSAGE_START: 'POST_MESSAGE_START',
  POST_MESSAGE_SUCCESS: 'POST_MESSAGE_SUCCESS',
  POST_MESSAGE_ERROR: 'POST_MESSAGE_ERROR',

  // get bot message
  GET_BOT_MESSAGE_START: 'GET_BOT_MESSAGE_START',
  GET_BOT_MESSAGE_SUCCESS: 'GET_BOT_MESSAGE_SUCCESS',
  GET_BOT_MESSAGE_ERROR: 'GET_BOT_MESSAGE_ERROR',

  // get user data
  GET_USER_START: 'GET_USER_START',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_ERROR: 'GET_USER_ERROR',

  // bot answer
  ANSWER: 'ANSWER',
};

export default types;
